Remove AWX references
stackhpc/azimuth-sample-appliance pull request #1
Opened 2023-08-21 15:55 UTC by sd109

I'm in the process of writing up some docs on developing custom Azimuth apps and noticed the docs here are outdated. Given I'm not all that familiar with the new CaaS operator, could you give the README a quick read through to check that it still makes sense that and that everything left in does apply to the new non-AWX spec.

2023-08-21 15:56 UTC, sd109 commented
Has this appliance ever been tested with the CaaS operator?

2023-08-29 08:50 UTC, JohnGarbutt approved these changes

2023-09-01 09:10 UTC, assumptionsandg requested changes
Some fixes to README.md

2023-09-01 09:10 UTC, assumptionsandg commented on README.md
> +    uiMetaUrl: https://raw.githubusercontent.com/stackhpc/azimuth-sample-appliance/master/ui-meta/sample-appliance.yaml
```suggestion
    uiMetaUrl: https://raw.githubusercontent.com/stackhpc/azimuth-sample-appliance/master/ui-meta/sample-appliance.yml
```

2023-09-01 09:10 UTC, assumptionsandg commented on README.md
> +    gitVersion: master
```suggestion
    gitVersion: main
```

2023-09-04 08:10 UTC, merged